### ISSUE TITLE
Can't login on skype

### ISSUE THREAD

**Issue by ArionWM** [Microsoft/AzureBot#123]
After clicked login link; "You have been signed out. You can now close this window." message appears on page. 

I tried signout & signin to azure portal.

Page link below.

regards.

https://azrbot.com/api/OAuthCallback?error=invalid_request&error_description=AADSTS90072%3a+The+user+doesn%27t+exist+in+the+directory%2c+user+needs+to+be+invited+as+guest+into+the+tenant%0d%0aTrace+ID%3a+05a05991-d23d-4385-a907-47fb67cdf70e%0d%0aCorrelation+ID%3a+87ca0d77-5cfb-4380-9236-7544dbe63fec%0d%0aTimestamp%3a+2016-12-28+11%3a27%3a10Z&state=H4sIAAAAAAAEAJ2PTU-DQBCGp5gYb_4FLyZeKMhHunA0UYPaJk1r2-vADrJSFrK7NOG_efOPdYwH7x7nzTzPzLucAVyglIasBY8Hr-xdIeEOACKRZxgLrGvykxpDP8niyi9FGPlJHKGIpRBJVINXNag1HRm7ZMy200DgjZYMJ-GPKMvvXeZ6XYj00Keb5OHpkC3CxSotjm9SPa5f9pNvSrtb7z93zZKFvT6RsegUM_908PmTqujdHOGW-ca5weZBYLsS585wKVV1qPGDzFyTC3BQFn6_XmFHcM3M9vvLtDjdvOKksYUrZbdmtI7k5s894_TZ9OPA-2ekWVT1TQEAAA2

**Comment by dtzar** [comment]
I just tested and I am able to login and use AzureBot on the Skype desktop channel.  @ArionWM Which skype client are you using?  Also - are you using a MSA account (versus AAD)?  Is it related to Issue #118?

**Comment by ArionWM** [comment]
Hi,
My skype version is: 7.30.64.105 on desktop.

I'm using MSA account (xxx@hotmail.com)

I'm not sure for related to issue #118

Regards.

**Comment by dtzar** [comment]
We do not currently support MSA accounts only AAD.  Please see Issue #108

**Comment by sgiovinetti** [comment]
I have the same issue but I use AAD. Any clue?

**Comment by dtzar** [comment]
Not sure - can you try to type the authentication number versus copy/paste?

**Comment by sgiovinetti** [comment]
The repro steps are the following:

I type “login” in the bot.
The bot replies asking to click this link https://login.microsoftonline.com/common/oauth2/authorize?resource=https:%2F%2Fmanagement.core.windows.net%2F&client_id=88443132-9b52-485d-90ed-49f37efd1c2b&response_type=code&haschrome=1&redirect_uri=https:%2F%2Fazrbot.com%2Fapi%2FOAuthCallback&x-client-SKU=PCL.Desktop&x-client-Ver=3.12.0.827&x-client-CPU=x64&x-client-OS=Microsoft+Windows+NT+6.2.9200.0&state=dXNlcklkPTI5JTNhMWEyMkhvNmR5Tzd5Tk53NTN2b0pPamdvUzM0YVE5aGpEeUpCMy1YRkc5eUNrWVVDcE4xTm9LajlacnBfYUtOaDYmYm90SWQ9MjglM2E5YTM4YWZmZS00ZmEwLTQ5M2MtYjgwMi00MzJhODNkODg0MmYmY29udmVyc2F0aW9uSWQ9MjklM2ExYTIySG82ZHlPN3lOTnc1M3ZvSk9qZ29TMzRhUTloakR5SkIzLVhGRzl5Q2tZVUNwTjFOb0tqOVpycF9hS05oNiZzZXJ2aWNlVXJsPWh0dHBzJTNhJTJmJTJmc21iYS50cmFmZmljbWFuYWdlci5uZXQlMmZhcGlzJTJmJmNoYW5uZWxJZD1za3lwZSZsb2NhbGU9ZW41


1.       I copy and paste the link in IE using inprivate browsing so that no active sessions etc. can interfere

2.       I login using my azure login <username>@<mycompany>.com

3.       I tab out and choose personal account instead of work or school (this is because I have two azure tenants with the same userid).

4.       The work/school account is the production azure and it is linked to my company AAD

5.       The personal account is dev/test azure with its own AAD not connected to the company AD. I want the bot to login to this one therefore I choose personal account.

6.       I insert the pwd of my personal account

7.       I receive a page that says “You have been signed out. You can now close this window.”
The page url of the above page is:
https://azrbot.com/api/OAuthCallback?error=invalid_request&error_description=AADSTS90072%3a+The+user+doesn%27t+exist+in+the+directory%2c+user+needs+to+be+invited+as+guest+into+the+tenant%0d%0aTrace+ID%3a+f8ee4c76-0d0d-4020-8ae5-cf36883a3243%0d%0aCorrelation+ID%3a+8ce17577-66c7-4567-bb7b-a867755e1843%0d%0aTimestamp%3a+2017-02-16+16%3a22%3a55Z&state=dXNlcklkPTI5JTNhMWEyMkhvNmR5Tzd5Tk53NTN2b0pPamdvUzM0YVE5aGpEeUpCMy1YRkc5eUNrWVVDcE4xTm9LajlacnBfYUtOaDYmYm90SWQ9MjglM2E5YTM4YWZmZS00ZmEwLTQ5M2MtYjgwMi00MzJhODNkODg0MmYmY29udmVyc2F0aW9uSWQ9MjklM2ExYTIySG82ZHlPN3lOTnc1M3ZvSk9qZ29TMzRhUTloakR5SkIzLVhGRzl5Q2tZVUNwTjFOb0tqOVpycF9hS05oNiZzZXJ2aWNlVXJsPWh0dHBzJTNhJTJmJTJmc21iYS50cmFmZmljbWFuYWdlci5uZXQlMmZhcGlzJTJmJmNoYW5uZWxJZD1za3lwZSZsb2NhbGU9ZW41<https://azrbot.com/api/OAuthCallback?error=invalid_request&error_description=AADSTS90072%3a+The+user+doesn%25>


Thanks

**Comment by dtzar** [comment]
Ok this makes more sense now.  You are using a personal [MSA] account (even if that user is present inside your own AAD tenant).  I'd be willing to bet that if you create a new work AAD account (i.e. Stefano@mydomain.onmicrosoft.com) in the directory where your Azure subscription is present and login with that work-based AAD account AzureBot will work.

**Comment by sgiovinetti** [comment]
Thanks, that was the issue!

Now it works.

**Comment by sgiovinetti** [comment]
Hello,
I had a new login problem now with a different user.

In particular, the user is an AAD account and the error during the login phase is AADSTS90093: Does not have access to consent.

Which type of permissions should the AAD user have for let it working?

Please advise.
Thanks.
